rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.2.0
gemfile:
  - rails-4.0.gemfile
  - rails-4.1.gemfile
  - rails-4.2.0.gemfile
script: bundle exec rake
after_success: bundle exec codeclimate-test-reporter
